# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-03 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_time', models.DateTimeField(verbose_name=b'date published')),
                ('event_location', models.CharField(max_length=200)),
                ('fee', models.IntegerField()),
                ('quota', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
    ]
