# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170912_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'\xe6\x97\xa5\xe6\x99\x82'),
        ),
    ]
