# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170914_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='members',
        ),
    ]
